name: Hello World

on:
  push:
    tags:
      - '*'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print message
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "Hello, world!"
