name: Build and Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and test
      run: |
        # Your build and test commands here
    - name: Deploy
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "hello world !"
